### ISSUE TITLE
Make this repo public

### ISSUE THREAD

**Issue by eirikbacker** [nrkno/core-css#1]

**Comment by mfolkeseth** [comment]
Why don't we just remove the .npmrc and push the button? Can I :)

**Comment by eirikbacker** [comment]
@mfolkeseth The repo is public. Pushing to NPM is awaiting due to https://github.com/nrkno/core-css/pull/7 which will change file paths, and I need to talk with @mariuslundgard before pushing the PR :)

**Comment by eirikbacker** [comment]
This repo is public on github, but seems we need to figure out the nrk vs. npm logic to public-source on npm as well
