### ISSUE TITLE
Switch to break-point sizes in em

### ISSUE THREAD

**Issue by Saegrov** [nrkno/core-css#14]
In Yr our current break points are defined in EMs and for consistency across browsers we would prefer it to stay this way:
https://zellwk.com/blog/media-query-units/

**Comment by Saegrov** [comment]
@eirikbacker Is this possible for other NRK applications?

**Comment by Saegrov** [comment]
There has also been the opposite discussion in twitter bootstrap:
https://github.com/twbs/bootstrap/pull/17403

**Comment by eirikbacker** [comment]
Very well spotted @Saegrov ! I have tested quite a bit (http://nrkqueries.playcode.io/) in IE11+, Edge, Safari, Opera, Firefox and Chrome, and find that `rem` and `em` now behaves equally. Supporting the suggestion - PR coming shortly
