### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by akselnordal** [nrkno/core-css#16]
For local development of apps dependent on the core-* packages (without internets) - it would be very convenient to install the core-* packages from npm (nrk or public, if open sourced)

**Comment by mfolkeseth** [comment]
I feel like this issue will resolve this one as well
https://github.com/nrkno/core-css/issues/1

**Comment by mfolkeseth** [comment]
#1

**Comment by mfolkeseth** [comment]
#1

**Comment by eirikbacker** [comment]
That's the plan, just need a final check on https://github.com/nrkno/core-css/pull/7 :)

**Comment by eirikbacker** [comment]
Concider it done @akselnordal @mfolkeseth 🎉
