### ISSUE TITLE
Add breakpoint for 'extra large' screens?

### ISSUE THREAD

**Issue by bratberg** [nrkno/core-css#17]
Should we consider adding another breakpoint and grid-selectors (`nrk-xl-XofX` etc.) to make it easier to adjust content for extra large screens? ("992px and up" feels kind of low considering a lot of users have screen resolutions of 1920x1080 and 2560x1440). Maybe 1200px/75rem or 1440px/90rem?

**Comment by eirikbacker** [comment]
Agreed! Bootstrap uses 75rem and foundation does not have any xl-breakpoint. I suggest  introducing a breakpoint at 1440/90rem though, as over 18% of user sessions are comes from devices with screens lager than 1440 (numbers form analytics april 2017). All in favour? 🌮

**Comment by eirikbacker** [comment]
Do you want to make a PR @bratberg ? :)
