### ISSUE TITLE
Add aspects to core-css

### ISSUE THREAD

**Issue by eirikbacker** [nrkno/core-css#24]
The most common aspect sizes are:
9:16, 3:4, 1:1, 3:2, 4:3, 16:9
Suggestions for additional or removing aspects @mfolkeseth and @Isdoda ?

**Comment by Isdoda** [comment]
Where is 9:16 used? Or are these common aspects on internet in general? Not NRK.no?

**Comment by Isdoda** [comment]
Where is 9:16 used? Or are these common aspects on internet in general, not NRK.no?

**Comment by eirikbacker** [comment]
9:16 is used in some social medias and portrait photos for mobile. This format was requested by super. In my opinion the most used aspects of NRK is first priority.

**Comment by Isdoda** [comment]
3:4, 16:9, 1:1 are the most common for nrk.no. We do altso have 1:4, but it's not used that much. In addition we have all the aspects for the front page, but i suppose it will be to much to include all of them? 
![image](https://user-images.githubusercontent.com/14125035/27829178-7bb86192-60c0-11e7-9f7a-6d8593000fa5.png)

**Comment by mfolkeseth** [comment]
Skip 9:16 and 3:4. Height scales nicely with width.

**Comment by eirikbacker** [comment]
This is such a simple thing to implement, so I suggest instead we make a best practice guide on image handling in general. Will be brought up in a front end forum soon.

**Comment by leftieFriele** [comment]
Working with a best practice guide is cool, but I'd still find it valueable to have the aspect ratio CSS tricks in core-css rather than having to google them every time :)
There are scenarios where we can't just trust the images to be in the correct form, so having .nrk-asp-169 or similar to slap on a container would be pretty neat.

**Comment by eirikbacker** [comment]
Can surely reopen @leftieFriele :) do you have any thoughts on which formats should be available? :)

**Comment by mfolkeseth** [comment]
- 16:9
- 9:16
- 4:3
