### ISSUE TITLE
Buttons should have smooth borders on Retina screens

### ISSUE THREAD

**Issue by mariuslundgard** [nrkno/core-css#30]
On Retina screens the button borders are slightly cut off/cropped.

![image](https://user-images.githubusercontent.com/406933/31265067-27bdb3ca-aa6d-11e7-9455-79a7b114dbe1.png)

**Comment by eirikbacker** [comment]
Can not seem to reproduce, maybe you can demo for me @mariuslundgard ? :)

**Comment by jorgeneidem** [comment]
Can confirm. Looking weird on LG 4K external display, as well as on Macbook 15" Retina display.
![screen shot 2017-11-14 at 15 57 37](https://user-images.githubusercontent.com/4020663/32786604-b510d8c8-c954-11e7-9c59-9e20297b6a0b.jpg)
