### ISSUE TITLE
Bold-strong Etica blir ødelagt dobbeltbold

### ISSUE THREAD

**Issue by formfett** [nrkno/core-css#37]
Etica-fonter på nrk.no/artikkel blir boldet av nettleseren. Fonten er allerede bold, og nettleseren bolder denne igjen, og da blir den ødelagt. Se f.eks h2+strong-elementet *Færre sjårører* i denne artikkelen: https://www.nrk.no/norge/forerlose-busser-pa-veiene-om-kort-tid-1.13798565

Her er en gif som viser hvordan den er og hvordan den egentlig skal være:
![bold-font](https://user-images.githubusercontent.com/8984470/33324941-4cf5c8e0-d451-11e7-9a4c-e852db34bb74.gif)

**Comment by eirikbacker** [comment]
det må nok rapporteres til NRK.no teamet- er feil måte de laster fonten her, men vet de har en oppgave i todo på å rydde i font
