### ISSUE TITLE
Default font

### ISSUE THREAD

**Issue by mfolkeseth** [nrkno/core-css#46]
Having a hard time overriding [this](https://github.com/nrkno/core-css/blob/master/lib/core-css.css#L4) in an intuitive way. I want to have a different default font, wile benefiting from `core-css`. Am I missing something? My best options ATM are wrapping the whole app in a class or using `!important` 😭

**Comment by eirikbacker** [comment]
core CSS should be loaded or bundled before your own CSS. Overwriting is then just defining html { font-family: somethingelse } :)

**Comment by eirikbacker** [comment]
Seems like this is not a core css issue- do you get SuperLFTEtica og you du not load core CSS? And how is this font included? :)

**Comment by mfolkeseth** [comment]
Ok, so, after some further digging it seems like, in Chrome OSX, at least, this doesn't fly very well with buttons. 
```
html { font-family: 'LFTEticaSuper'; }
```
Work just fine with paragraphs and links, but buttons get computed fonts as such:
![screen shot 2018-05-11 at 09 14 22](https://user-images.githubusercontent.com/7047431/39911495-e44cec48-54fb-11e8-91fb-7d8928c69e2f.png)
