### ISSUE TITLE
how to start writing with stylemark

### ISSUE THREAD

**Issue by ikhwanb** [nrkno/core-css#48]
Hi, i stumbled upon your repo while trying to figure out how to use stylemark.
I am using your code as basis to create our own style guide. I can't get to display a section with example & html at the bottom of it. I only managed to get raw html itself in grey box. Appreciate if you could assist me thanks a lot

**Comment by eirikbacker** [comment]
Hi @ikhwanb ! Cool you use stylemark too :) the trick is just adding code with backticks and a filename (instead of only extension) 
```
```filename.html
code here
```
see for example https://raw.githubusercontent.com/nrkno/core-css/master/lib/colors.md
