### ISSUE TITLE
Expose version number

### ISSUE THREAD

**Issue by mariuslundgard** [nrkno/core-css#49]
Wouldn't it be nice to expose the version number in core-css.css?

```js
/* @nrk/core-css v1.8.2 */
/* Base
---------------------------------------------------------------- */
html {
  font: 100%/1.5 'Helvetica Neue', Helvetica, Arial, sans-serif;
  text-size-adjust: 100%;           /* Mobile font size */
  -webkit-tap-highlight-color: transparent;
}
...
```

This way, when using https://static.nrk.no/core-css/latest/core-css.css, it would be easy to figure out which version is actually used.

**Comment by eirikbacker** [comment]
Much agreed! This should actually apply to all packages on static.nrk.no I think :) I hope no one uses `https://static.nrk.no/core-css/latest/core-css.css` but rather `https://static.nrk.no/core-css/latest/core-css.min.css` - the minified version now have version number exposed, as this is easy to add in the build step 👍
