### ISSUE TITLE
Dead url in the readme

### ISSUE THREAD

**Issue by turbolego** [nrkno/core-css#51]
From the readme:

> Adding fonts and icons
> In order to use NRKs core fonts and icons, see these related projects:
> https://github.com/nrkno/core-fonts

This link is dead/404.

Just a heads up ^_^

**Comment by eirikbacker** [comment]
Hello Tobias! Well spotted and thanks for comment! This is actually because `core-fonts` is only available when logged in to NRK Github - we can not open source the fonts due to licensing. I'll clarify the readme 👍
