### ISSUE TITLE
Possibility to consume as NPM package

### ISSUE THREAD

**Issue by eirikbacker** [nrkno/core-css#52]

**Comment by htor** [comment]
what is the desired usage? `import coreCss from 'core-css'` should result in a string, or object?
there's an unstandard, but commonly used field in `package.json` named `style` which points to the main css file, which most tools (like rollup, browserify) understands when they overload the `import` function to inline, etc.

**Comment by eirikbacker** [comment]
Have done some research, and I guess importing "placeholder classes" in Sass, Less, and Stylus might be solution. Also, we should export the pure css, and the css using the `@apply` standard?

All of the following markups makes the same output:
**Sass**
```
%nrk-button {
  color: red;
  background: gray;
  &:hover { opacity: .5; }
  &div > svg { display: none }
}

.selector {
  @extend %nrk-button;
  .nested {
    margin: 3px;
  }
}
```

**Stylus**
```
$nrk-button {
  color: red; background: gray;
  &:hover { opacity: .5; }
  div& > svg { display: none }
}

.selector {
  @extends $nrk-button;
  .nested {
    margin: 3px;
  }
}
```

**Less**
```
.nrk-button() {
  color: red; background: gray;
  &:hover { opacity: .5; }
  div& > svg { display: none }
}

.selector {
  .nrk-button();
  .nested {
    margin: 3px;
  }
}
```

**CSS Modules**
```
.nrk-button {
  color: red;
  background: gray;
}
.nrk-button:hover { opacity: .5; }
div.nrk-button > svg { display: none }

.selector {
	composes: nrk-button;
	display: inline-block;
	border: 1px solid black;
}
```

**Should be tested**
https://github.com/garthdb/postcss-inherit/
https://github.com/dehuszar/postcss-reference/
https://github.com/pascalduez/postcss-apply/ (In use in [cssnext](http://cssnext.io/) Suggested W3C standard, but stale. Might be replaced by https://meowni.ca/posts/part-theme-explainer/)
https://github.com/csstools/postcss-preset-env unfortunately does not support composition
