### ISSUE TITLE
Add standalone loading animation

### ISSUE THREAD

**Issue by bjrk** [nrkno/core-css#79]
Add loading animation that can be used when users have to wait for data to be loaded.
@eirikbacker mentioned that the animation of the `nrk-button is-busy` could maybe be used

**Comment by eirikbacker** [comment]
Context: this is a huge surface with no data yet? More like a skeleton loading screen maybe? :) https://uxdesign.cc/what-you-should-know-about-skeleton-screens-a820c45a571a

**Comment by bjrk** [comment]
For this case skeleton could work great :)

**Comment by eirikbacker** [comment]
In that case - this is more a design system issue of NRK.no, and not a `core-css` matter. I suggest this is a question for the designers of this product, and let's advocate/look further into a more design-heavy system for NRK.no or maybe all products :)

**Comment by bjrk** [comment]
agree! unless needs rise from other products it is not a `core-css` matter
