### ISSUE TITLE
Discuss; does `yarn build -- --watch` make sense?

### ISSUE THREAD

**Issue by mariuslundgard** [nrkno/core-css#8]
In `bin/build.js` it's possible to watch changes to the `src` directory. But it doesn't actually the `dist` directory.

What is the underlying need `node bin/build --watch` is trying to solve, and how can we achieve it?

**Comment by eirikbacker** [comment]
Short answer - nope, does not make sense for now, since nothing needs to build to run :) Was partially removed on redesigned documentation, now fully removed :)
